import { BaseAdapter, AdapterConfig, AdapterResult } from './base.js';
import { generateHybridRules, generateToolConfig } from './rules-generator.js';
import path from 'path';
import fs from 'fs-extra';

export class AiderAdapter extends BaseAdapter {
  private currentMode?: string;
  private currentRole?: string;
  private currentGate?: string;

  constructor(projectPath: string, options?: { mode?: string; role?: string; gate?: string }) {
    const config: AdapterConfig = {
      name: 'aider',
      displayName: 'Aider',
      configDir: '.aider',
      rulesDir: '',
      ruleExtension: '.md'
    };
    super(config, projectPath);
    this.currentMode = options?.mode;
    this.currentRole = options?.role;
    this.currentGate = options?.gate;
  }

  /**
   * Generate Aider's CONVENTIONS.md file
   * Aider uses this for coding conventions
   */
  getRulesContent(): string {
    const hybridRules = generateHybridRules({
      tool: 'aider',
      currentMode: this.currentMode,
      currentRole: this.currentRole,
      currentGate: this.currentGate
    });

    return `${hybridRules}

---

# Aider-Specific Instructions

## Voice/Chat Commands
When chatting with Aider, you can reference RIPER concepts:
- "Switch to execute mode" → Aider will load Execute mode context
- "Check protection on src/core/" → Aider checks protection levels
- "I need to plan this feature" → Aider switches to Plan mode

## File Context Commands
- "/add <file>" with protection check
- "/read <file>" always allowed
- "/architect" for design discussions (Design gate)
- "/code" for implementation (Development+ gate)

## Mode-Aware Commit Messages
Aider generates commit messages prefixed with mode:
- [Ω₁-Research] "Explored options for..."
- [Ω₄-Execute] "Implemented feature X..."
- [Ω₅-Review] "Fixed bug in..."

## Test-Driven Development
Aider respects Testing gate requirements:
- Auto-runs tests in Testing gate
- Blocks commits if tests fail in strict mode
- Suggests test cases during Plan mode
`;
  }

  /**
   * Aider uses .aider.conf.yml for configuration
   */
  async install(dryRun: boolean = false): Promise<AdapterResult> {
    const result = await super.install(dryRun);
    if (!result.success) return result;

    const extraFiles: string[] = [];

    const configPath = path.join(this.projectPath, '.aider.conf.yml');
    extraFiles.push(configPath);
    const conventionsPath = path.join(this.projectPath, 'CONVENTIONS.md');
    extraFiles.push(conventionsPath);

    if (!dryRun) {
      try {
        // Create Aider configuration
        const config = `# Aider Configuration for RIPER
# Generated by RIPER-for-All

# Load RIPER conventions
conventions: ${conventionsPath}

# Model settings
model: gpt-4o
weak-model: gpt-4o-mini

# RIPER Mode Settings (updated via 'riper mode <mode>')
# Current mode: ${this.currentMode || 'research'}
# Current role: ${this.currentRole || 'developer'}
# Current gate: ${this.currentGate || 'design'}

# Auto-commits with mode prefix
auto-commits: true
commit-prompt: |
  Generate a concise commit message that starts with [Ωₓ-ModeName]
  based on the RIPER mode: ${this.currentMode || 'research'}

# Lint and test settings (gate-aware)
lint-cmd: npm run lint
test-cmd: npm test
`;

        await fs.writeFile(configPath, config, 'utf8');

        // Create CONVENTIONS.md
        await fs.writeFile(conventionsPath, this.getRulesContent(), 'utf8');
      } catch (error) {
        return { success: false, message: `Failed to create Aider config: ${error}` };
      }
    }

    return {
      ...result,
      filesCreated: [...(result.filesCreated ?? []), ...extraFiles]
    };
  }

  /**
   * Update Aider configuration with current mode/role/gate
   */
  async updateConfig(mode?: string, role?: string, gate?: string): Promise<void> {
    const configPath = path.join(this.projectPath, '.aider.conf.yml');
    const conventionsPath = path.join(this.projectPath, 'CONVENTIONS.md');
    
    try {
      // Update conventions.md with new BMAD context
      const newContent = generateHybridRules({
        tool: 'aider',
        currentMode: mode || this.currentMode,
        currentRole: role || this.currentRole,
        currentGate: gate || this.currentGate
      });
      
      await fs.writeFile(conventionsPath, `${newContent}\n\n# Aider-Specific Instructions\n\n(See full instructions in CONVENTIONS.md)\n`, 'utf8');

      // Update config file mode references
      if (await fs.pathExists(configPath)) {
        let config = await fs.readFile(configPath, 'utf8');
        
        if (mode) {
          config = config.replace(/# Current mode: .*/, `# Current mode: ${mode}`);
        }
        if (role) {
          config = config.replace(/# Current role: .*/, `# Current role: ${role}`);
        }
        if (gate) {
          config = config.replace(/# Current gate: .*/, `# Current gate: ${gate}`);
        }
        
        await fs.writeFile(configPath, config, 'utf8');
      }

      this.currentMode = mode || this.currentMode;
      this.currentRole = role || this.currentRole;
      this.currentGate = gate || this.currentGate;
    } catch {
      // Silently fail - config update is not critical
    }
  }

  /**
   * Get Aider-specific commands reference
   */
  getCommandsReference(): string {
    return `
# Aider + RIPER Command Reference

## Mode Switching (via Aider chat)
- "Switch to research mode" or "/research"
- "Switch to plan mode" or "/plan"
- "Switch to execute mode" or "/execute"
- "Switch to review mode" or "/review"

## Protection Commands
- "Check protection on <path>"
- "Is <file> protected?"
- "What's the protection level?"

## Gate Commands
- "What gate are we in?"
- "Advance to next gate"
- "Show gate status"

## Role Commands
- "I am the architect" (switch role)
- "Switch to QA role"
- "What role am I?"
`;
  }
}
